# -*- coding: utf-8 -*-
"""Hangman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOe6sdLR-wxe8hNLbyvq6rxSDIRNHHlc
"""

import random

# Hangman art
hangman_art = [
    '''
    +---+
    |   |
        |
        |
        |
        |
  =========''',
    '''
    +---+
    |   |
    O   |
        |
        |
        |
  =========''',
    '''
    +---+
    |   |
    O   |
    |   |
        |
        |
  =========''',
    '''
    +---+
    |   |
    O   |
   /|   |
        |
        |
  =========''',
    '''
    +---+
    |   |
    O   |
   /|\  |
        |
        |
  =========''',
    '''
    +---+
    |   |
    O   |
   /|\  |
   /    |
        |
  =========''',
    '''
    +---+
    |   |
    O   |
   /|\  |
   / \  |
        |
  ========='''
]
word_list = ["SANJANA", "SUSHMITA", "TANIYA", "CHETNA", "PRACHI"]
chosen_word = random.choice(word_list).lower()
print(chosen_word)
display = ['_' for _ in chosen_word]
lives = len(hangman_art) - 1
game_over = False
while not game_over:
    print(hangman_art[len(hangman_art) - lives - 1])
    print(' '.join(display))
    guessed_letter = input("Guess a letter: ").lower()
    if guessed_letter in chosen_word:
        for position in range(len(chosen_word)):
            if chosen_word[position] == guessed_letter:
                display[position] = guessed_letter

        print(' '.join(display))
    else:
        lives -= 1
        print(f"Incorrect guess! Lives left: {lives}")
  # Checking if the player has won
    if '_' not in display:
        game_over = True
        print("Congratulations! You win!")
  # Checking if the player has lost
    elif lives == 0:
        game_over = True
        print("Sorry, you lose! The word was:", chosen_word)