# -*- coding: utf-8 -*-
"""Stock

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNgUTfNZVLlO4hgT90lFmHtzgxOLsDci
"""

import requests

class StockPortfolio:
    def __init__(self):
        self.portfolio = {}

    def add_stock(self, symbol, quantity):
        if symbol in self.portfolio:
            self.portfolio[symbol] += quantity
        else:
            self.portfolio[symbol] = quantity

    def remove_stock(self, symbol, quantity):
        if symbol in self.portfolio:
            if self.portfolio[symbol] >= quantity:
                self.portfolio[symbol] -= quantity
                if self.portfolio[symbol] == 0:
                    del self.portfolio[symbol]
            else:
                print("Not enough shares to remove.")
        else:
            print("Stock not found in portfolio.")

    def get_portfolio_value(self):
        total_value = 0
        for symbol, quantity in self.portfolio.items():
            price = self.get_stock_price(symbol)
            if price is not None:
                total_value += price * quantity
        return total_value

    def get_stock_price(self, symbol):
        api_key = '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'
        url = f'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={symbol}&apikey={api_key}'
        response = requests.get(url)
        data = response.json()
        if 'Global Quote' in data:
            return float(data['Global Quote']['05. price'])
        else:
            print(f"Failed to fetch data for {symbol}.")
            return None
portfolio = StockPortfolio()

portfolio.add_stock('AAPL', 10)
portfolio.add_stock('GOOGL', 5)
portfolio.add_stock('MSFT', 8)

portfolio.remove_stock('AAPL', 3)

portfolio_value = portfolio.get_portfolio_value()
print(f"Portfolio value: ${portfolio_value:.2f}")

from google.colab import drive
drive.mount('/content/drive')